-- =============================================================================
--  Presence48 — schema initial
--
--  Ce fichier est la traduction exacte de docs/diagrammes/D2-modele-donnees.md.
--  Toute divergence entre les deux est un defaut : le diagramme et la migration
--  doivent etre modifies dans le meme commit.
--
--  SQL volontairement portable : les memes migrations sont rejouees sur H2 en
--  mode compatibilite PostgreSQL par les tests (ENF7, contrainte B6). Aucun type
--  ni fonction propre a PostgreSQL n'est utilise ici.
-- =============================================================================

-- -----------------------------------------------------------------------------
--  Referentiel — en lecture seule pour l'application (Q1, hors perimetre)
-- -----------------------------------------------------------------------------
CREATE TABLE promotion (
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(100) NOT NULL,
    CONSTRAINT uk_promotion_nom UNIQUE (nom)
);

CREATE TABLE etudiant (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom          VARCHAR(150) NOT NULL,
    -- RG21 : un etudiant appartient a une et une seule promotion.
    promotion_id BIGINT       NOT NULL,
    CONSTRAINT fk_etudiant_promotion FOREIGN KEY (promotion_id) REFERENCES promotion (id)
);

CREATE INDEX idx_etudiant_promotion ON etudiant (promotion_id);

-- -----------------------------------------------------------------------------
--  Sessions de cours
--  Nommee session_cours et non session : SESSION est un mot reserve du standard
--  SQL, que H2 en mode PostgreSQL ne tolere pas toujours comme nom de table.
-- -----------------------------------------------------------------------------
CREATE TABLE session_cours (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titre         VARCHAR(200)             NOT NULL,
    promotion_id  BIGINT                   NOT NULL,
    -- RG6 : le code est unique et non devinable.
    code          VARCHAR(12)              NOT NULL,
    ouverture_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    -- RG1 : expiration_at = ouverture_at + 15 minutes.
    expiration_at TIMESTAMP WITH TIME ZONE NOT NULL,
    -- RG19, RG22 : nul tant que la session est ouverte. La cloture est un acte
    -- du formateur, distinct de l'expiration du code.
    cloturee_at   TIMESTAMP WITH TIME ZONE NULL,
    CONSTRAINT uk_session_code UNIQUE (code),
    CONSTRAINT fk_session_promotion FOREIGN KEY (promotion_id) REFERENCES promotion (id)
);

CREATE INDEX idx_session_promotion ON session_cours (promotion_id);

-- -----------------------------------------------------------------------------
--  Presences
-- -----------------------------------------------------------------------------
CREATE TABLE presence (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id  BIGINT                   NOT NULL,
    etudiant_id BIGINT                   NOT NULL,
    -- RG15 : Q14 exige que l'origine d'une presence se voie.
    source      VARCHAR(9)               NOT NULL,
    marquee_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    -- RG4 : un etudiant n'est present qu'une fois a une meme session. Tenue par
    -- la base et non par le service seul : c'est ce qui garantit le 409.
    CONSTRAINT uk_presence_session_etudiant UNIQUE (session_id, etudiant_id),
    CONSTRAINT ck_presence_source CHECK (source IN ('ETUDIANT', 'FORMATEUR')),
    CONSTRAINT fk_presence_session FOREIGN KEY (session_id) REFERENCES session_cours (id),
    CONSTRAINT fk_presence_etudiant FOREIGN KEY (etudiant_id) REFERENCES etudiant (id)
);

CREATE INDEX idx_presence_session ON presence (session_id);
CREATE INDEX idx_presence_etudiant ON presence (etudiant_id);

-- -----------------------------------------------------------------------------
--  Exercices
--  statut : voir docs/diagrammes/D4-etats-exercice.md. DEPOSE n'est pas persiste,
--  c'est un etat de passage : a la fin du POST, l'exercice est deja soit en
--  attente d'assignation, soit en attente de relecture.
-- -----------------------------------------------------------------------------
CREATE TABLE exercice (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id  BIGINT                   NOT NULL,
    -- l'auteur de l'exercice
    etudiant_id BIGINT                   NOT NULL,
    -- RG10 : URL http(s), validee a l'entree.
    lien        VARCHAR(500)             NOT NULL,
    statut      VARCHAR(30)              NOT NULL,
    depose_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    -- RG9 : un seul exercice par etudiant et par session.
    CONSTRAINT uk_exercice_session_etudiant UNIQUE (session_id, etudiant_id),
    CONSTRAINT ck_exercice_statut CHECK (statut IN (
        'EN_ATTENTE_ASSIGNATION',
        'EN_ATTENTE_RELECTURE',
        'EN_COURS_DE_RELECTURE',
        'RELU')),
    CONSTRAINT fk_exercice_session FOREIGN KEY (session_id) REFERENCES session_cours (id),
    CONSTRAINT fk_exercice_etudiant FOREIGN KEY (etudiant_id) REFERENCES etudiant (id)
);

CREATE INDEX idx_exercice_session ON exercice (session_id);
CREATE INDEX idx_exercice_etudiant ON exercice (etudiant_id);
CREATE INDEX idx_exercice_statut ON exercice (statut);

-- -----------------------------------------------------------------------------
--  Relectures
--  Il n'existe deliberement AUCUNE table relecteur : le relecteur est un
--  etudiant dans un etat, pas un acteur distinct (section 2 du cahier des
--  charges). Le role est porte par relecteur_id.
--
--  La ligne est creee des le tirage au sort, avec note, commentaire,
--  consultee_at et rendue_at a NULL : c'est ce qui permet de compter les
--  relectures en attente du tableau formateur (RG16).
-- -----------------------------------------------------------------------------
CREATE TABLE relecture (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- RG7 : un seul relecteur par exercice, garanti par l'unicite.
    exercice_id  BIGINT                   NOT NULL,
    -- RG2, RG8 : jamais l'auteur de l'exercice. Cette regle ne peut PAS etre
    -- tenue par un CHECK : il faudrait comparer avec exercice.etudiant_id, qui
    -- vit dans une autre table. Elle est donc tenue par le service, et couverte
    -- par le test unitaire exige par la contrainte B6.
    relecteur_id BIGINT                   NOT NULL,
    -- RG3 : entier de 0 a 20 ; nul jusqu'au rendu.
    note         INTEGER                  NULL,
    commentaire  VARCHAR(2000)            NULL,
    assignee_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    -- RG12 : instant ou la relecture commence, c'est-a-dire ou le relecteur
    -- ouvre l'exercice. Tant qu'il est nul, l'auteur peut remplacer son lien.
    consultee_at TIMESTAMP WITH TIME ZONE NULL,
    -- RG13 : une fois pose, la relecture est definitive.
    rendue_at    TIMESTAMP WITH TIME ZONE NULL,
    CONSTRAINT uk_relecture_exercice UNIQUE (exercice_id),
    CONSTRAINT ck_relecture_note CHECK (note IS NULL OR (note >= 0 AND note <= 20)),
    -- une relecture rendue porte forcement une note et un commentaire
    CONSTRAINT ck_relecture_rendue CHECK (
        rendue_at IS NULL OR (note IS NOT NULL AND commentaire IS NOT NULL)),
    CONSTRAINT fk_relecture_exercice FOREIGN KEY (exercice_id) REFERENCES exercice (id),
    CONSTRAINT fk_relecture_relecteur FOREIGN KEY (relecteur_id) REFERENCES etudiant (id)
);

CREATE INDEX idx_relecture_relecteur ON relecture (relecteur_id);
CREATE INDEX idx_relecture_rendue ON relecture (rendue_at);
